/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/posts.json": {
        parameters: {
            query?: {
                tags?: components["parameters"]["Tags"];
                page?: components["parameters"]["Page"];
                limit?: components["parameters"]["LimitPosts"];
                md5?: string | string[];
                only?: ("id" | "source" | "pixiv_id" | "md5" | "file_ext" | "file_size" | "file_url" | "large_file_url" | "preview_file_url" | "media_asset" | "image_height" | "image_width" | "created_at" | "updated_at" | "uploader_id" | "approver_id" | "parent_id" | "rating" | "score" | "up_score" | "down_score" | "fav_count" | "tag_string" | "tag_string_general" | "tag_string_artist" | "tag_string_copyright" | "tag_string_character" | "tag_string_meta" | "tag_count" | "tag_count_general" | "tag_count_artist" | "tag_count_copyright" | "tag_count_character" | "tag_count_meta" | "last_comment_bumped_at" | "last_commented_at" | "last_noted_at" | "has_active_children" | "has_children" | "has_large" | "has_visible_children" | "bit_flags" | "is_banned" | "is_deleted" | "is_flagged" | "is_pending" | "uploader" | "updater" | "approver" | "parent" | "children")[] | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Posts list */
        get: operations["list_posts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}.json": {
        parameters: {
            query?: {
                only?: ("id" | "source" | "pixiv_id" | "md5" | "file_ext" | "file_size" | "file_url" | "large_file_url" | "preview_file_url" | "media_asset" | "image_height" | "image_width" | "created_at" | "updated_at" | "uploader_id" | "approver_id" | "parent_id" | "rating" | "score" | "up_score" | "down_score" | "fav_count" | "tag_string" | "tag_string_general" | "tag_string_artist" | "tag_string_copyright" | "tag_string_character" | "tag_string_meta" | "tag_count" | "tag_count_general" | "tag_count_artist" | "tag_count_copyright" | "tag_count_character" | "tag_count_meta" | "last_comment_bumped_at" | "last_commented_at" | "last_noted_at" | "has_active_children" | "has_children" | "has_large" | "has_visible_children" | "bit_flags" | "is_banned" | "is_deleted" | "is_flagged" | "is_pending" | "uploader" | "updater" | "approver" | "parent" | "children")[] | string;
            };
            header?: never;
            path: {
                id: components["schemas"]["postID"];
            };
            cookie?: never;
        };
        /** @description Show post */
        get: operations["get_post"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/random.json": {
        parameters: {
            query?: {
                tags?: components["parameters"]["Tags"];
                only?: ("id" | "source" | "pixiv_id" | "md5" | "file_ext" | "file_size" | "file_url" | "large_file_url" | "preview_file_url" | "media_asset" | "image_height" | "image_width" | "created_at" | "updated_at" | "uploader_id" | "approver_id" | "parent_id" | "rating" | "score" | "up_score" | "down_score" | "fav_count" | "tag_string" | "tag_string_general" | "tag_string_artist" | "tag_string_copyright" | "tag_string_character" | "tag_string_meta" | "tag_count" | "tag_count_general" | "tag_count_artist" | "tag_count_copyright" | "tag_count_character" | "tag_count_meta" | "last_comment_bumped_at" | "last_commented_at" | "last_noted_at" | "has_active_children" | "has_children" | "has_large" | "has_visible_children" | "bit_flags" | "is_banned" | "is_deleted" | "is_flagged" | "is_pending" | "uploader" | "updater" | "approver" | "parent" | "children")[] | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get random post */
        get: operations["get_random_post"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users.json": {
        parameters: {
            query?: {
                search?: {
                    id?: number | number[];
                    name?: string;
                    created_at?: number;
                    updated_at?: number;
                    name_matches?: string;
                    min_level?: string;
                    max_level?: string;
                    current_user_first?: string;
                    order?: "name" | "post_upload_count" | "post_update_count" | "note_count";
                };
                only?: ("id" | "name" | "level" | "inviter_id" | "post_update_count" | "note_update_count" | "post_upload_count" | "favorite_count" | "unread_dmail_count" | "is_banned" | "bit_prefs" | "theme" | "favorite_tags" | "blacklisted_tags" | "comment_threshold" | "timezone" | "per_page" | "default_image_size" | "custom_css" | "upload_points" | "last_forum_read_at" | "last_logged_in_at" | "created_at" | "updated_at")[] | string;
                tags?: components["parameters"]["Tags"];
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get list of users */
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}.json": {
        parameters: {
            query?: {
                only?: ("id" | "name" | "level" | "inviter_id" | "post_update_count" | "note_update_count" | "post_upload_count" | "favorite_count" | "unread_dmail_count" | "is_banned" | "bit_prefs" | "theme" | "favorite_tags" | "blacklisted_tags" | "comment_threshold" | "timezone" | "per_page" | "default_image_size" | "custom_css" | "upload_points" | "last_forum_read_at" | "last_logged_in_at" | "created_at" | "updated_at")[] | string;
                tags?: components["parameters"]["Tags"];
            };
            header?: never;
            path: {
                id: components["schemas"]["userID"];
            };
            cookie?: never;
        };
        /** @description Get user */
        get: operations["get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists.json": {
        parameters: {
            query?: {
                search?: {
                    id?: number | number[];
                    name?: string;
                    group_name?: string;
                    created_at?: number;
                    updated_at?: number;
                    is_deleted?: boolean;
                    is_banned?: boolean;
                    any_other_name_like?: string;
                    any_name_matches?: string;
                    url_matches?: string;
                    any_name_or_url_matches?: string;
                    order?: "name" | "updated_at" | "post_count" | "custom";
                };
                only?: ("id" | "name" | "group_name" | "other_names" | "is_banned" | "is_deleted" | "created_at" | "updated_at" | "members" | "urls" | "wiki_page" | "tag_alias" | "tag")[] | string;
                limit?: components["parameters"]["Limit"];
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_artists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists/{id}.json": {
        parameters: {
            query?: {
                only?: ("id" | "name" | "group_name" | "other_names" | "is_banned" | "is_deleted" | "created_at" | "updated_at" | "members" | "urls" | "wiki_page" | "tag_alias" | "tag")[] | string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** @description Get artist */
        get: operations["get_artist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artist_urls.json": {
        parameters: {
            query?: {
                search?: {
                    id?: number | number[];
                    artist_id?: number | number[];
                    url?: string;
                    is_active?: boolean;
                };
                only?: ("id" | "artist_id" | "url" | "created_at" | "updated_at" | "is_active")[] | string;
                limit?: components["parameters"]["Limit"];
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get artist urls */
        get: operations["get_artist_urls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_tags"];
        put?: never;
        post: operations["list_tags_use_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{id}.json": {
        parameters: {
            query?: {
                only?: ("id" | "name" | "post_count" | "category" | "created_at" | "updated_at" | "is_deprecated" | "words" | "wiki_page" | "artist" | "antecedent_alias" | "consequent_aliases" | "antecedent_implications" | "dtext_links")[] | string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** @description Get tag */
        get: operations["get_tag"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/iqdb_queries.json": {
        parameters: {
            query?: {
                search?: {
                    id?: components["schemas"]["postID"];
                    url?: string;
                    hash?: string;
                };
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["iqdb_query"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autocomplete.json": {
        parameters: {
            query?: {
                search?: {
                    type: "tag" | "user" | "artist";
                    query: string;
                };
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get autocomplete */
        get: operations["get_autocomplete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source.json": {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get source info by URL */
        get: operations["get_source_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media_assets.json": {
        parameters: {
            query?: {
                search?: {
                    id?: string;
                    md5?: string;
                    ai_tags_match?: string;
                };
                only?: ("id" | "created_at" | "updated_at" | "md5" | "file_ext" | "file_size" | "image_width" | "image_height" | "duration" | "status" | "file_key" | "is_public" | "pixel_hash" | "variants")[] | string;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get media assets */
        get: operations["get_media_assets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media_assets/{id}.json": {
        parameters: {
            query?: {
                only?: ("id" | "created_at" | "updated_at" | "md5" | "file_ext" | "file_size" | "image_width" | "image_height" | "duration" | "status" | "file_key" | "is_public" | "pixel_hash" | "variants")[] | string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** @description Get media asset by id */
        get: operations["get_media_asset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media_metadata.json": {
        parameters: {
            query?: {
                search?: {
                    id?: string;
                    media_asset_id?: string;
                    metadata?: string | {
                        [key: string]: unknown;
                    };
                } | {
                    [key: string]: unknown;
                };
                only?: ("id" | "created_at" | "updated_at" | "media_asset_id" | "metadata")[] | string;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_media_metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        artist: {
            /** @description Artist ID */
            id: number;
            name: string;
            group_name: string;
            other_names: string[];
            is_banned: boolean;
            is_deleted: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            members?: unknown[];
            urls?: components["schemas"]["artistUrl"][];
            wiki_page?: {
                /** @description Wiki ID */
                id: number;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                updated_at: string;
                title: string;
                body: string;
                is_locked: boolean;
                other_names: string[];
                is_deleted: boolean;
            };
            tag_alias?: unknown;
            tag?: components["schemas"]["tag"];
        };
        artists: components["schemas"]["artist"][];
        artistUrl: {
            /** @description Artist URL ID */
            id: number;
            /** @description The Artist ID */
            artist_id: number;
            /** Format: uri */
            url: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            is_active: boolean;
        };
        artistUrls: components["schemas"]["artistUrl"][];
        autocomplete: {
            /**
             * @description The type of the autocomplete item, must be "tag"
             * @constant
             */
            type: "tag";
            /** @description The label of the autocomplete item */
            label: string;
            /** @description The value of the autocomplete item */
            value: string;
            /**
             * @description The category of the autocomplete item, must be 1 for artists
             * @constant
             */
            category: 1;
        }[] | {
            /**
             * @description The type of the autocomplete item, must be "tag-word"
             * @constant
             */
            type: "tag-word";
            /** @description The label of the autocomplete item */
            label: string;
            /** @description The value of the autocomplete item */
            value: string;
            /**
             * @description The category of the autocomplete item, includes [0, 1, 3, 4, 5]
             * @enum {number}
             */
            category: 0 | 1 | 3 | 4 | 5;
            /** @description The count of posts associated with the tag, must be >= 0 */
            post_count: number;
            tag: components["schemas"]["tag"];
        }[] | {
            /**
             * @description The type of the autocomplete item, must be "user"
             * @constant
             */
            type: "user";
            /** @description The label of the autocomplete item */
            label: string;
            /** @description The value of the autocomplete item */
            value: string;
            id: components["schemas"]["userID"];
            /**
             * @description The level of the user
             * @enum {string}
             */
            level: "member" | "gold" | "platinum" | "builder" | "admin";
        }[];
        /** @description Access denied */
        forbidden: unknown;
        iqdbResult: {
            hash: string;
            post_id: components["schemas"]["postID"];
            score: number;
            signature: {
                avglf: [
                    number,
                    number,
                    number
                ];
                sig: [
                    number[],
                    number[],
                    number[]
                ];
            };
            post: components["schemas"]["post"];
        };
        /** @description The number of results to show per page */
        limit: number;
        mediaAsset: {
            /** @description Asset ID */
            id: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            md5: string;
            file_ext: string;
            file_size: number;
            image_width: number;
            image_height: number;
            duration?: number | null;
            status: string;
            file_key: string;
            is_public: boolean;
            pixel_hash: string;
            variants: {
                type: string;
                /** Format: uri */
                url: string;
                width: number;
                height: number;
                file_ext: string;
            }[];
        };
        mediaAssets: components["schemas"]["mediaAsset"][];
        mediaMetadata: {
            /** @description Media Metadata ID */
            id: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description Asset ID */
            media_asset_id: number;
            metadata: {
                [key: string]: unknown;
            };
        };
        mediaMetadataList: components["schemas"]["mediaMetadata"][];
        /** @description Not found */
        notFound: {
            success: boolean;
            error: string;
            message: string;
        };
        /** @description Determines the list of attributes that will be returned */
        only: string;
        /** @description The number of results to show per page */
        page: number;
        post: {
            id: components["schemas"]["postID"];
            /** @description The source of the post */
            source: string;
            /** @description The Pixiv ID of the post */
            pixiv_id?: number | null;
            /** @description The MD5 hash of the file */
            md5: string;
            /**
             * @description The file extension
             * @enum {string}
             */
            file_ext: "jpg" | "png" | "gif" | "avif" | "mp4" | "webp" | "webm" | "swf" | "zip";
            /** @description The size of the file */
            file_size: number;
            /**
             * Format: uri
             * @description The URL of the file
             */
            file_url: string;
            /**
             * Format: uri
             * @description The URL of the large file
             */
            large_file_url: string;
            /**
             * Format: uri
             * @description The URL of the preview file
             */
            preview_file_url: string;
            /** @description The media asset associated with the post */
            media_asset: components["schemas"]["mediaAsset"];
            /** @description The height of the image */
            image_height: number;
            /** @description The width of the image */
            image_width: number;
            /**
             * Format: date-time
             * @description The timestamp when the post was created
             */
            created_at: string;
            /**
             * Format: date-time
             * @description The timestamp when the post was last updated
             */
            updated_at: string;
            /** @description The ID of the user who uploaded the post */
            uploader_id: number;
            /** @description The ID of the user who approved the post */
            approver_id?: number | null;
            /** @description The ID of the parent post */
            parent_id: components["schemas"]["postID"];
            rating: ("g" | "s" | "q" | "e") | null;
            /** @description The score of the post */
            score: number;
            /** @description The up score of the post */
            up_score: number;
            /** @description The down score of the post */
            down_score: number;
            /** @description The number of favorites */
            fav_count: number;
            /** @description The tags associated with the post */
            tag_string: string;
            /** @description The general tags associated with the post */
            tag_string_general: string;
            /** @description The artist tags associated with the post */
            tag_string_artist: string;
            /** @description The copyright tags associated with the post */
            tag_string_copyright: string;
            /** @description The character tags associated with the post */
            tag_string_character: string;
            /** @description The meta tags associated with the post */
            tag_string_meta: string;
            /** @description The total number of tags */
            tag_count: number;
            /** @description The number of general tags */
            tag_count_general: number;
            /** @description The number of artist tags */
            tag_count_artist: number;
            /** @description The number of copyright tags */
            tag_count_copyright: number;
            /** @description The number of character tags */
            tag_count_character: number;
            /** @description The number of meta tags */
            tag_count_meta: number;
            /** @description The timestamp when the last comment was bumped */
            last_comment_bumped_at?: string | null;
            /** @description The timestamp when the last comment was added */
            last_commented_at?: string | null;
            /** @description The timestamp when the last note was added */
            last_noted_at?: string | null;
            /** @description Indicates whether the post has active children */
            has_active_children: boolean;
            /** @description Indicates whether the post has children */
            has_children: boolean;
            /** @description Indicates whether the post has a large version */
            has_large: boolean;
            /** @description Indicates whether the post has visible children */
            has_visible_children: boolean;
            /** @description The bit flags of the post */
            bit_flags: number;
            /** @description Indicates whether the post is banned */
            is_banned: boolean;
            /** @description Indicates whether the post is deleted */
            is_deleted: boolean;
            /** @description Indicates whether the post is flagged */
            is_flagged: boolean;
            /** @description Indicates whether the post is pending */
            is_pending: boolean;
            uploader?: components["schemas"]["user"];
            updater?: components["schemas"]["user"];
            approver?: components["schemas"]["user"];
            parent?: components["schemas"]["post"];
            children?: components["schemas"]["post"][];
        };
        /** @description The post ID */
        postID: number;
        posts: components["schemas"]["post"][];
        postsLimit: components["schemas"]["limit"];
        source: {
            page_url: string | null;
            image_urls: string[];
            artist: {
                display_name: string | null;
                username: string | null;
                profile_urls: string[];
                artists: {
                    /** @description Artist ID */
                    id: number;
                    name: string;
                }[];
            };
            tags: string[][];
            artist_commentary: {
                title: string | null;
                description: string | null;
                dtext_title: string | null;
                dtext_description: string | null;
            };
        };
        tag: {
            /** @description Tag ID */
            id: number;
            name: string;
            post_count: number;
            /**
             * @description https://danbooru.donmai.us/wiki_pages/api%3Atags#:~:text=timestamp-,Category,-Value
             * @enum {number}
             */
            category: 0 | 1 | 3 | 4 | 5;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            is_deprecated: boolean;
            words: string[];
            wiki_page?: {
                /** @description Wiki ID */
                id: number;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                updated_at: string;
                title: string;
                body: string;
                is_locked: boolean;
                other_names: string[];
                is_deleted: boolean;
            };
            artist?: components["schemas"]["artist"];
            antecedent_alias?: string;
            consequent_aliases?: string;
            antecedent_implications?: string;
            dtext_links?: string;
        };
        tags: components["schemas"]["tag"][];
        /** @description Authentication failed */
        unauthorized: unknown;
        user: {
            id: components["schemas"]["userID"];
            /** @description The name of the user */
            name: string;
            /**
             * @description The level of the record
             * @enum {string}
             */
            level: "10" | "20" | "30" | "31" | "32" | "40" | "50";
            /** @description The ID of the inviter, must be greater than 0 */
            inviter_id: number | null;
            /** @description The count of post updates */
            post_update_count: number;
            /** @description The count of note updates */
            note_update_count: number;
            /** @description The count of post uploads */
            post_upload_count: number;
            /** @description The count of favorites */
            favorite_count: number;
            /** @description The count of unread direct messages */
            unread_dmail_count: number;
            /** @description Indicates whether the record is banned */
            is_banned: boolean;
            /** @description Bit preferences, each bit stores a boolean value */
            bit_prefs: number;
            /**
             * @description The theme of the record
             * @enum {string}
             */
            theme: "light" | "dark";
            /** @description The favorite tags of the record */
            favorite_tags: string;
            /** @description The blacklisted tags of the record */
            blacklisted_tags: string;
            /** @description The comment threshold of the record */
            comment_threshold: number;
            /** @description The timezone of the record */
            timezone: string;
            /** @description The number of items per page, must be between 1 and 200 */
            per_page: number;
            /**
             * @description The default image size of the record
             * @enum {string}
             */
            default_image_size: "large" | "original";
            /** @description The custom CSS of the record */
            custom_css: string;
            /** @description The upload points of the record */
            upload_points: number;
            /**
             * Format: date-time
             * @description The timestamp when the forum was last read
             */
            last_forum_read_at: string;
            /**
             * Format: date-time
             * @description The timestamp when the user last logged in
             */
            last_logged_in_at: string;
            /**
             * Format: date-time
             * @description The timestamp when the record was created
             */
            created_at: string;
            /**
             * Format: date-time
             * @description The timestamp when the record was last updated
             */
            updated_at: string;
        };
        /** @description The User ID */
        userID: number;
        users: components["schemas"]["user"][];
    };
    responses: {
        /** @description The given parameters could not be parsed */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": unknown;
            };
        };
        /** @description Authentication failed */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["unauthorized"];
            };
        };
        /** @description Access denied */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["forbidden"];
            };
        };
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["notFound"];
            };
        };
    };
    parameters: {
        Limit: number;
        LimitPosts: components["schemas"]["postsLimit"];
        Page: components["schemas"]["page"];
        Tags: string | string[];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_posts: {
        parameters: {
            query?: {
                tags?: components["parameters"]["Tags"];
                page?: components["parameters"]["Page"];
                limit?: components["parameters"]["LimitPosts"];
                md5?: string | string[];
                only?: ("id" | "source" | "pixiv_id" | "md5" | "file_ext" | "file_size" | "file_url" | "large_file_url" | "preview_file_url" | "media_asset" | "image_height" | "image_width" | "created_at" | "updated_at" | "uploader_id" | "approver_id" | "parent_id" | "rating" | "score" | "up_score" | "down_score" | "fav_count" | "tag_string" | "tag_string_general" | "tag_string_artist" | "tag_string_copyright" | "tag_string_character" | "tag_string_meta" | "tag_count" | "tag_count_general" | "tag_count_artist" | "tag_count_copyright" | "tag_count_character" | "tag_count_meta" | "last_comment_bumped_at" | "last_commented_at" | "last_noted_at" | "has_active_children" | "has_children" | "has_large" | "has_visible_children" | "bit_flags" | "is_banned" | "is_deleted" | "is_flagged" | "is_pending" | "uploader" | "updater" | "approver" | "parent" | "children")[] | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["posts"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    get_post: {
        parameters: {
            query?: {
                only?: ("id" | "source" | "pixiv_id" | "md5" | "file_ext" | "file_size" | "file_url" | "large_file_url" | "preview_file_url" | "media_asset" | "image_height" | "image_width" | "created_at" | "updated_at" | "uploader_id" | "approver_id" | "parent_id" | "rating" | "score" | "up_score" | "down_score" | "fav_count" | "tag_string" | "tag_string_general" | "tag_string_artist" | "tag_string_copyright" | "tag_string_character" | "tag_string_meta" | "tag_count" | "tag_count_general" | "tag_count_artist" | "tag_count_copyright" | "tag_count_character" | "tag_count_meta" | "last_comment_bumped_at" | "last_commented_at" | "last_noted_at" | "has_active_children" | "has_children" | "has_large" | "has_visible_children" | "bit_flags" | "is_banned" | "is_deleted" | "is_flagged" | "is_pending" | "uploader" | "updater" | "approver" | "parent" | "children")[] | string;
            };
            header?: never;
            path: {
                id: components["schemas"]["postID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["post"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    get_random_post: {
        parameters: {
            query?: {
                tags?: components["parameters"]["Tags"];
                only?: ("id" | "source" | "pixiv_id" | "md5" | "file_ext" | "file_size" | "file_url" | "large_file_url" | "preview_file_url" | "media_asset" | "image_height" | "image_width" | "created_at" | "updated_at" | "uploader_id" | "approver_id" | "parent_id" | "rating" | "score" | "up_score" | "down_score" | "fav_count" | "tag_string" | "tag_string_general" | "tag_string_artist" | "tag_string_copyright" | "tag_string_character" | "tag_string_meta" | "tag_count" | "tag_count_general" | "tag_count_artist" | "tag_count_copyright" | "tag_count_character" | "tag_count_meta" | "last_comment_bumped_at" | "last_commented_at" | "last_noted_at" | "has_active_children" | "has_children" | "has_large" | "has_visible_children" | "bit_flags" | "is_banned" | "is_deleted" | "is_flagged" | "is_pending" | "uploader" | "updater" | "approver" | "parent" | "children")[] | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["post"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    list_users: {
        parameters: {
            query?: {
                search?: {
                    id?: number | number[];
                    name?: string;
                    created_at?: number;
                    updated_at?: number;
                    name_matches?: string;
                    min_level?: string;
                    max_level?: string;
                    current_user_first?: string;
                    order?: "name" | "post_upload_count" | "post_update_count" | "note_count";
                };
                only?: ("id" | "name" | "level" | "inviter_id" | "post_update_count" | "note_update_count" | "post_upload_count" | "favorite_count" | "unread_dmail_count" | "is_banned" | "bit_prefs" | "theme" | "favorite_tags" | "blacklisted_tags" | "comment_threshold" | "timezone" | "per_page" | "default_image_size" | "custom_css" | "upload_points" | "last_forum_read_at" | "last_logged_in_at" | "created_at" | "updated_at")[] | string;
                tags?: components["parameters"]["Tags"];
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["users"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    get_user: {
        parameters: {
            query?: {
                only?: ("id" | "name" | "level" | "inviter_id" | "post_update_count" | "note_update_count" | "post_upload_count" | "favorite_count" | "unread_dmail_count" | "is_banned" | "bit_prefs" | "theme" | "favorite_tags" | "blacklisted_tags" | "comment_threshold" | "timezone" | "per_page" | "default_image_size" | "custom_css" | "upload_points" | "last_forum_read_at" | "last_logged_in_at" | "created_at" | "updated_at")[] | string;
                tags?: components["parameters"]["Tags"];
            };
            header?: never;
            path: {
                id: components["schemas"]["userID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["user"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    list_artists: {
        parameters: {
            query?: {
                search?: {
                    id?: number | number[];
                    name?: string;
                    group_name?: string;
                    created_at?: number;
                    updated_at?: number;
                    is_deleted?: boolean;
                    is_banned?: boolean;
                    any_other_name_like?: string;
                    any_name_matches?: string;
                    url_matches?: string;
                    any_name_or_url_matches?: string;
                    order?: "name" | "updated_at" | "post_count" | "custom";
                };
                only?: ("id" | "name" | "group_name" | "other_names" | "is_banned" | "is_deleted" | "created_at" | "updated_at" | "members" | "urls" | "wiki_page" | "tag_alias" | "tag")[] | string;
                limit?: components["parameters"]["Limit"];
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["artists"];
                };
            };
        };
    };
    get_artist: {
        parameters: {
            query?: {
                only?: ("id" | "name" | "group_name" | "other_names" | "is_banned" | "is_deleted" | "created_at" | "updated_at" | "members" | "urls" | "wiki_page" | "tag_alias" | "tag")[] | string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["artist"];
                };
            };
        };
    };
    get_artist_urls: {
        parameters: {
            query?: {
                search?: {
                    id?: number | number[];
                    artist_id?: number | number[];
                    url?: string;
                    is_active?: boolean;
                };
                only?: ("id" | "artist_id" | "url" | "created_at" | "updated_at" | "is_active")[] | string;
                limit?: components["parameters"]["Limit"];
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["artistUrls"];
                };
            };
        };
    };
    list_tags: {
        parameters: {
            query?: {
                search?: {
                    id?: number | number[];
                    name?: string;
                    category?: (0 | 1 | 3 | 4 | 5) | (0 | 1 | 3 | 4 | 5)[];
                    post_count?: number;
                    is_deprecated?: boolean;
                    created_at?: number;
                    updated_at?: number;
                    fuzzy_name_matches?: string;
                    name_matches?: string;
                    name_normalize?: string | string[];
                    name_or_alias_matches?: string;
                    hide_empty?: string;
                    is_empty?: string;
                    order?: "name" | "date" | "count" | "similarity" | "custom";
                };
                only?: ("id" | "name" | "post_count" | "category" | "created_at" | "updated_at" | "is_deprecated" | "words" | "wiki_page" | "artist" | "antecedent_alias" | "consequent_aliases" | "antecedent_implications" | "dtext_links")[] | string;
                limit?: components["parameters"]["Limit"];
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["tags"];
                };
            };
        };
    };
    list_tags_use_post: {
        parameters: {
            query?: never;
            header: {
                "X-HTTP-Method-Override": "get";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    limit?: components["schemas"]["limit"];
                    page?: components["schemas"]["page"];
                    only?: string;
                    search?: {
                        id?: number | number[];
                        name?: string;
                        category?: (0 | 1 | 3 | 4 | 5) | (0 | 1 | 3 | 4 | 5)[];
                        post_count?: number;
                        is_deprecated?: boolean;
                        created_at?: number;
                        updated_at?: number;
                        fuzzy_name_matches?: string;
                        name_matches?: string;
                        name_normalize?: string | string[];
                        name_or_alias_matches?: string;
                        hide_empty?: string;
                        is_empty?: string;
                        order?: "name" | "date" | "count" | "similarity" | "custom";
                    };
                };
            };
        };
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["tags"];
                };
            };
        };
    };
    get_tag: {
        parameters: {
            query?: {
                only?: ("id" | "name" | "post_count" | "category" | "created_at" | "updated_at" | "is_deprecated" | "words" | "wiki_page" | "artist" | "antecedent_alias" | "consequent_aliases" | "antecedent_implications" | "dtext_links")[] | string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["tag"];
                };
            };
        };
    };
    iqdb_query: {
        parameters: {
            query?: {
                search?: {
                    id?: components["schemas"]["postID"];
                    url?: string;
                    hash?: string;
                };
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["iqdbResult"];
                };
            };
        };
    };
    get_autocomplete: {
        parameters: {
            query?: {
                search?: {
                    type: "tag" | "user" | "artist";
                    query: string;
                };
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["autocomplete"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    get_source_info: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["source"];
                };
            };
        };
    };
    get_media_assets: {
        parameters: {
            query?: {
                search?: {
                    id?: string;
                    md5?: string;
                    ai_tags_match?: string;
                };
                only?: ("id" | "created_at" | "updated_at" | "md5" | "file_ext" | "file_size" | "image_width" | "image_height" | "duration" | "status" | "file_key" | "is_public" | "pixel_hash" | "variants")[] | string;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["mediaAssets"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    get_media_asset: {
        parameters: {
            query?: {
                only?: ("id" | "created_at" | "updated_at" | "md5" | "file_ext" | "file_size" | "image_width" | "image_height" | "duration" | "status" | "file_key" | "is_public" | "pixel_hash" | "variants")[] | string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["mediaAsset"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    get_media_metadata: {
        parameters: {
            query?: {
                search?: {
                    id?: string;
                    media_asset_id?: string;
                    metadata?: string | {
                        [key: string]: unknown;
                    };
                } | {
                    [key: string]: unknown;
                };
                only?: ("id" | "created_at" | "updated_at" | "media_asset_id" | "metadata")[] | string;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["mediaMetadataList"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
